# https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md

#组件信息
component: scf
name: bilibili_tool

#组件参数配置
inputs:
  name: ${name}_scf
  enableRoleAuth: false
  src: ./bin/publish/
  handler: index.main_handler
  runtime: CustomRuntime
  region: ap-guangzhou # 函数所在区域，默认广州
  description: This is a function in ${app} application.
  memorySize: 128
  initTimeout: 30
  timeout: 86400
  asyncRunEnable: true
  traceEnable: true
  events: # 根据自己的需要修改
    - timer: # 每日任务触发器
        parameters:
          name: DailyTask
          cronExpression: "0 30 12 * * * *"
          enable: true
          argument: Daily
    - timer: # 天选抽奖触发器
        parameters:
          name: LiveLotteryTask
          cronExpression: "0 0 */4 * * * *"
          enable: true
          argument: LiveLottery
    - timer: # 自动取关
        parameters:
          name: UnfollowBatchedTask
          cronExpression: "0 0 0 * * MON *"
          enable: true
          argument: UnfollowBatched
  environment:
    variables: # 根据自己的需要修改
      Ray_CloseConsoleWhenEnd: 1
      Ray_BiliBiliCookies__1: _uuid=6CFB55B1-6BE9-E5D0-FD0F-D8FE7CE7E4F203163infoc; buvid3=4C860E3C-7DC6-4C38-BF80-5137AE6A285A13426infoc; buvid_fp=4C860E3C-7DC6-4C38-BF80-5137AE6A285A13426infoc; SESSDATA=291694c3%2C1639292035%2C92ae0%2A61; bili_jct=b48dac29b675711b3faf7bd06a1c6c0e; DedeUserID=2677673; DedeUserID__ckMd5=a8243bc9d30f2dab; sid=aiaenxb7; CURRENT_FNVAL=80; blackside_state=1; rpdid=|(J~|)kR|kkk0J'uYkR||lYJR; fingerprint3=808d36236b0bf9283ccede9a5f6d962c; buvid_fp_plain=4C860E3C-7DC6-4C38-BF80-5137AE6A285A13426infoc; LIVE_BUVID=AUTO7216246267351515; PVID=4; bsource=search_baidu; fingerprint=279d75b3c0c92e0f3d8f10704323d117; fingerprint_s=42c35eada30bc16ddfd0ad8711b522c9; bfe_id=c5d4c382b0a326b5f45ec37e1aea9efa # cookie，必填
